import { useState } from 'react';
import BookingDialog, { type Booking } from './components/BookingDialog';
const nav = [['Training','training'],['Coaching','coaching'],['Schedule','schedule'],['Memberships','memberships']];
const schedule = [['Monday','Strength','07:00','18:00'],['Tuesday','Conditioning','07:00','19:00'],['Wednesday','Strength','07:00','18:00'],['Thursday','Conditioning','07:00','19:00'],['Friday','Strength','07:00','17:30'],['Saturday','Full body','09:00','11:00']];
export default function App() {
 const [menu, setMenu] = useState(false);
 const [booking, setBooking] = useState<Booking | null>(null);
 const [coaches, setCoaches] = useState(false);
 const book = (plan = 'First session', session?: string) => { setMenu(false); setBooking({plan,session}); };
 return <><a className="skip-link" href="#main">Skip to content</a><header className="header"><a href="#" className="wordmark" aria-label="Forge 44 home">FORGE <span>44</span></a><nav className={menu ? 'navigation is-open' : 'navigation'} id="navigation" aria-label="Main navigation">{nav.map(([label,id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}</nav><button className="button header-book" onClick={() => book()}>Book session</button><button className="menu-button" aria-controls="navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? 'Close' : 'Menu'}<span aria-hidden="true">{menu ? '×' : '☰'}</span></button></header>
 <main id="main">
 <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><h1 id="hero-title">TRAIN HEAVY.<br/>MOVE WELL.<br/>STAY USEFUL.</h1><p>Strength and conditioning built<br className="desktop-break"/> around expert coaching.</p><div className="hero-actions"><button className="button" onClick={() => book()}>Book your first session</button><a className="text-link" href="#memberships">View memberships</a></div><div className="hero-foot">Serious training. Expert coaching. No circus.</div></div><div className="hero-photo"><img src="/images/hero.jpg" alt="Athletes training with free weights and squat racks on an industrial gym floor" fetchPriority="high"/><div className="unit-sign"><span>UNIT</span><strong>44</strong></div><div className="photo-caption"><span>A workshop for stronger people.</span><span>FORGE 44</span></div></div></section>
 <section className="intro section-wrap" id="training"><h2>Everything you need.<br/>Nothing you don't.</h2><div><p>Strength is built. One good rep, one considered session, one week at a time.</p><p>We bring strength, conditioning and mobility together with a plan that moves you forward. No random workouts. No crowded floor. Just good training, done properly.</p><div className="disciplines"><span>Strength</span><span>Conditioning</span><span>Mobility</span></div></div></section>
 <section className="floor"><div className="floor-photo"><img src="/images/floor.jpg" alt="Open training floor with rowing machines, a punching bag and functional training equipment" loading="lazy"/><span className="image-note">Inside Unit 44</span></div><div className="floor-copy"><h2>Built for<br/>training.</h2><p>A former workshop. A new kind of work. An open, considered space with the right tools and room to use them.</p><ul><li>Free weights & lifting platforms</li><li>Racks you don't have to queue for</li><li>Conditioning equipment</li><li>Space to move, carry & recover</li></ul><a className="text-link" href="#schedule">Find your time on the floor</a></div></section>
 <section className="coaching section-wrap" id="coaching"><div className="coaching-copy"><h2>Coaching that<br/>actually coaches.</h2><p>More than someone watching the clock.</p><p>We learn how you move, help you get the details right, and build a progression around your goals. From your first barbell session to your next personal best, you won't be figuring it out alone.</p><button className="text-link" aria-expanded={coaches} aria-controls="coach-details" onClick={() => setCoaches(!coaches)}>{coaches ? 'Close coach profiles' : 'Meet the coaches'} <span aria-hidden="true">{coaches ? '−' : '+'}</span></button>{coaches && <div id="coach-details" className="coach-details"><h3>Alex Morgan</h3><p>Head coach. Strength foundations, barbell technique and long-term progression.</p><h3>Sam Ellis</h3><p>Conditioning coach. Small-group sessions, movement quality and building work capacity.</p><small>Fictional team profiles for the Forge 44 concept.</small><button className="button" onClick={() => book('Personal coaching')}>Find your coach</button></div>}</div><figure className="coaching-photo"><img src="/images/coaching.jpg" alt="Lifter practising a barbell back squat inside a training rack" loading="lazy"/><figcaption>Good technique. Lasting progress.</figcaption></figure></section>
 <section className="options section-wrap"><div className="options-heading"><h2>Find your<br/>kind of work.</h2><p>Different ways to train.<br/>The same attention to detail.</p></div><div className="option-list">{[['Strength training','Build a strong foundation with focused barbell work and progressive programming.'],['Conditioning','Build the engine to match. Purposeful intervals, carries and full-body work.'],['Small-group coaching','Individual attention, shared effort. Structured sessions with a coach on the floor.'],['Personal coaching','Your goals. Your starting point. A training plan and coaching built around you.']].map(([title,copy]) => <details key={title}><summary>{title}<span aria-hidden="true">+</span></summary><p>{copy}</p><button className="text-link" onClick={() => book(title === 'Personal coaching' ? title : 'First session')}>Try a session</button></details>)}</div></section>
 <section className="schedule section-wrap" id="schedule"><div className="section-heading"><h2>Make time.<br/>Get stronger.</h2><div><p>Your week on the floor.</p><p className="muted">Coached sessions. All levels welcome.<br/>Choose a time to book your first session.</p></div></div><div className="timetable">{schedule.map(([day,type,...times]) => <div className="day" key={day}><h3><abbr title={day}>{day.slice(0,3).toUpperCase()}</abbr></h3><p>{type}</p><div>{times.map(time => <button key={time} onClick={() => book('First session',`${day} · ${time}`)} aria-label={`Book ${type}, ${day} at ${time}`}>{time}<span aria-hidden="true">↗</span></button>)}</div></div>)}</div><p className="schedule-note">All times are local to the club. Sunday is for recovery.</p></section>
 <section className="memberships section-wrap" id="memberships"><div className="section-heading"><h2>Your training.<br/>Your commitment.</h2><p>Choose a rhythm you can keep.<br/>Expert coaching comes as standard.</p></div><div className="membership-list">{[['Drop in','Single training session','£20','/ session'],['8 sessions','8 coached sessions per month','£120','/ month'],['Unlimited','Unlimited group training','£165','/ month']].map(([name,desc,price,period]) => <article className="membership" key={name}><h3>{name}</h3><p>{desc}</p><div className="price">{price}<span>{period}</span></div><button className="text-link" onClick={() => book(name)} aria-label={`Choose ${name} membership`}>Choose plan <span aria-hidden="true">↗</span></button></article>)}</div><p className="membership-note">Monthly plans. No joining fee. Pricing shown for this fictional club concept.</p></section>
 <section className="final-cta"><div className="final-cta-photo"><img src="/images/plates.jpg" alt="An athlete loading a weight plate onto a barbell" loading="lazy"/></div><div className="final-cta-copy"><h2>YOUR FIRST SESSION<br/>STARTS HERE.</h2><p>Come in. Meet a coach. Train with us.</p><button className="button button-light" onClick={() => book()}>Book your first session</button></div></section>
 </main><footer className="footer"><div className="footer-main"><div><a className="wordmark" href="#">FORGE <span>44</span></a><p>Serious training.<br/>Expert coaching. No circus.</p></div><nav aria-label="Footer navigation">{nav.map(([label,id]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav><div><h3>On the floor</h3><p>Monday–Friday <span>06:00–21:00</span><br/>Saturday <span>08:00–14:00</span><br/>Sunday <span>Closed</span></p></div><div><h3>Find us</h3><p>Unit 44, Workshop Quarter<br/>Fictional location</p><a href="mailto:hello@forge44.example">hello@forge44.example</a><p className="social-placeholder">Instagram: @forge44 (fictional)</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Forge 44</span><span>Independent spirit. Shared effort.</span><span>A fictional club. A real commitment to good design.</span></div></footer><BookingDialog booking={booking} close={() => setBooking(null)}/></>;
}
